using UnityEngine;
using UnityEngine.Networking;

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;

public class SHCustomCertificateHandler : CertificateHandler
{
    private static readonly string CERT_KEY = "MIICizCCAfQCCQDwf4v6CJfa6TANBgkqhkiG9w0BAQsFADCBiTELMAkGA1UEBhMCa3IxDjAMBgNVBAgMBXNlb3VsMRAwDgYDVQQHDAdnYW5nbmFtMRMwEQYDVQQKDAptYW5nb25pZ2h0MRIwEAYDVQQLDAlhc2dhcmRpdW0xDDAKBgNVBAMMA2F3czEhMB8GCSqGSIb3DQEJARYSc2htaGxvdmVAbmF2ZXIuY29tMB4XDTE5MDIxMzE0MDYxN1oXDTE5MDMxNTE0MDYxN1owgYkxCzAJBgNVBAYTAmtyMQ4wDAYDVQQIDAVzZW91bDEQMA4GA1UEBwwHZ2FuZ25hbTETMBEGA1UECgwKbWFuZ29uaWdodDESMBAGA1UECwwJYXNnYXJkaXVtMQwwCgYDVQQDDANhd3MxITAfBgkqhkiG9w0BCQEWEnNobWhsb3ZlQG5hdmVyLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA9I4ydsDhikcLXt6UfzquTmuWhqpsEuQx+30I69voyRPoD5k3y42HDvBgolwCwximBfUuMX/+lpe9kBWC7Zk+dwldSmGB2mTM5gypLx3deU+uTTEnnO7dG1ARvF7NMwPXaqRsQpAEhvLkKUBNA61N7j9a5o12st/qU9WQUm5ycYECAwEAATANBgkqhkiG9w0BAQsFAAOBgQBkzdMbx9PT2UntCMSbRXnEWL8Qcxv2U1u8TjZph4qn1P11xG05DNCHHulOGVAKspUGkpyMw1/VoiaEKd2J7rPPHDJ6oZj5MsUm2weuERS9UOMDOjvBvfLmoZcPrR0TMPivu1EmyuoBtSab0X4JQbzYCVhqPlQ3RE2Mkh9gv8gS+w==";

    protected override bool ValidateCertificate(byte[] certificateData)
    {
        return CERT_KEY.Equals(System.Convert.ToBase64String(certificateData));
    }
}
